version: '3'
services:
  app:
    image: node:18
    tty: true
    ports:
        - '3000:3000'
        - '6006:6006'
    volumes:
        - .:/app
    working_dir: /app
    command: bash -c "yarn install && yarn start"
